[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "877c0c411976f67ae1923ff742ba97b7c125dfa6"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "f3d783124295fc5e804f953cc44595d711e8221b66163d3191acbba3193e6306"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "171477ef75514230dd794e7b2fee76a74b8935e0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "735db19abcb23802dbcca4bef516ea17c942e0b27098157258f8a8e491b4b267"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "b7fb6d68957d8f25cddfc30ac08f025069cbbc86"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "5a2b3575956cb742647cfdb517038a85693946a67dd91f2722f07250d2f427e5"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "6dc2e59ab2a14da9aacfc68ed5bb418873cc6f82"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "6b2e4740d9376956033313ed94f33ebe4450f3a91c48fb1450536beefc550f29"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "2bf61ed557217ba6bc5a97196b7b360a377ebf67"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "e7729911ec7b7d3aabcb302c518c60fb5bba3a9c9d511c04f0aee59c8271b7d5"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "riscv64"
git-tree-sha1 = "0587b0a048dc6489d053819510f5e34fd521f58f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "bfc16207a13597153a70c18d02cfa85a2f63407673a2062908f7789c80089fce"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "b5d0a96272adb886874b8e53eeec24d0cb48d8d3"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "17bdd9a68c47c0424ebd0780b2f7bb08e7bc666a51f1a512fbef7499d9cb88a8"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "139e0f3db8865948898af89d8cc903cfd8475556"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "ee81c4c0d725478e45e964facd4ca5e7fc1ce46f74ac26bd35ac0276cb40297b"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "3967327b2cf3e825a218ce5eba4885f35a1d86c0"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "ccd829d3d6161c5f2e7223f21121e1d803022e592c570e7733888083af6d3587"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "efdcc4994c7c0a822d88d141020503c707736ffc"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "5fdee8020cdea1ef392cec1f7d8dd35d05f3a23b6ce2d01c341d0f85627620da"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40300.0+0/GAP_pkg_datastructures.v1.40300.0.x86_64-unknown-freebsd.tar.gz"
