[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "0ad13cb04c39c6f145a4f1f1bebdc0f4e5722955"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "f6ef25fa78c03df2a1922e4b944fc5dbc38940a1c4fa0d71f8e1df518d901521"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "a2acb06a88f38e031461a5efcc487c474c261373"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "7ddc427c8a03ff5e40c7f04fcc6b851ae1f152dfac2cf5997ea871ba4228cd29"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "a06cae79733e98a439a32d835e3452ef52c90400"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "36847183c8f92b6932db2ac143e553b1c48238d00ad59c5dfc0e4f8d71477bba"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "d38edea9763f99c111e5be240cc37e813d7cc4dc"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "be7e4242c3fc7dda3848898e2a4a4263da699412abeaca6fc15770df0b33d9bb"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "32cff47f4663abe2d33afaf7006632e33a0e2858"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "d61640f9accf3e2d88188e17aeeb40986e717f4a4a39ce2bac9b4ecb41631654"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "riscv64"
git-tree-sha1 = "9e6709aaff382fc4500e5bdb260de8d9faa71c0e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "cd17de0fc1c17908a0f7104a2557767a0e096c594484106bf4c077f594ad5fd5"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "fd53a93c0196aeec4566ec0a9735bd73582ccbcc"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "39c071aa1b36eceb20474c0c1f50ea3144b31a7e1a4d79b7a427407672d6a148"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "fcd647076c03e9f4f24c18a8330da5b5cb4347a0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "d213866c50368234b95f902789d9b8c5da1c5f2b005ddfc6dd92e8fe88a8a952"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "bc39d65fb52352a40bad69d140c50e4cfae3fc9c"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "0efc947651355ad4f0c2d3eb4de87bd14f2f3bc124102b0793d106b732563d7e"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "0d041bcd5027c3c9ddfee777bc2485deb313ae56"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "f4aa67f1539d68036ea363535bc3d3392f27134b183e25fd019e8df949b5dabd"
    url = "https://github.com/lgoettgens/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v1.40100.0+0/GAP_pkg_datastructures.v1.40100.0.x86_64-unknown-freebsd.tar.gz"
